### ISSUE TITLE
Handle multiple matches

### ISSUE THREAD

**Issue by wayneashleyberry** [kevinburke/ssh_config#17]
Given the following scenario, the results are unexpected and there is no obvious work around.

```
Host *
 IdentityFile ~/.ssh/id_rsa

Host foo
 IdentityFile ~/.ssh/bar
```

```go
ssh_config.Get("foo", "IdentityFile") // "~/.ssh/id_rsa"
```

In this case, I get `~/.ssh/id_rsa` but I'm actually looking for `~/.ssh/bar`. The wildcard does indeed match, and should return but it should be possible to get all matches or at least see that there are multiple.

ie.

```go
func GetAll(alias, key string) []string
```

**Comment by kevinburke** [comment]
Oh interesting! I wonder how the `ssh` binary handles this situation? I need to go reread the manpage.

**Comment by wayneashleyberry** [comment]
@kevinburke I'm not entirely sure, but based on my usage of SSH in Go, it seems like multiple auth methods are supported. Perhaps `ssh` cycles through matching credentials and tries each until successful?

**Comment by wayneashleyberry** [comment]
I've been trying out this kind of pattern:

```go
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/kevinburke/ssh_config"
)

// Wrapper implemenration
type Wrapper struct {
	alias string
	conf  ssh_config.Config
}

// Get implementation
func (w *Wrapper) Get(key string) string {
	value, err := w.conf.Get(w.alias, key)
	if err != nil || value == "" {
		return ssh_config.Default(key)
	}
	return value
}

// GetAll implemenration
func GetAll(alias string) []Wrapper {
	w := []Wrapper{}

	f, _ := os.Open(filepath.Join(os.Getenv("HOME"), ".ssh", "config"))
	cfg, _ := ssh_config.Decode(f)
	for _, host := range cfg.Hosts {
		if host.Matches(alias) {
			w = append(w, Wrapper{
				alias: alias,
				conf: ssh_config.Config{
					Hosts: []*ssh_config.Host{host},
				},
			},
			)
		}
	}

	return w
}

func main() {
	alias := "foo"
	configs := GetAll(alias)
	for _, c := range configs {
		fmt.Println(c.Get("IdentityFile"))
	}
}
```

Given the following `~/.ssh/config`:

```
Host *
 AddKeysToAgent yes
 UseKeychain yes
 IdentityFile ~/.ssh/id_rsa

Host foo
 IdentityFile ~/.ssh/bar
```

The output look as follows:

```
~/.ssh/identity
~/.ssh/id_rsa
~/.ssh/bar
```

I guess having a `func GetAll(alias, key string) []string` doesn't really help, because I want to get values per host and then decide what to do with them.

**Comment by kevinburke** [comment]
From the manpage:

```
     IdentityFile
             Specifies a file from which the user's DSA, ECDSA, Ed25519 or RSA authentication identity is read.  The default is ~/.ssh/id_dsa, ~/.ssh/id_ecdsa,
             ~/.ssh/id_ed25519 and ~/.ssh/id_rsa.  Additionally, any identities represented by the authentication agent will be used for authentication unless
             IdentitiesOnly is set.  If no certificates have been explicitly specified by CertificateFile, ssh(1) will try to load certificate information from
             the filename obtained by appending -cert.pub to the path of a specified IdentityFile.

             Arguments to IdentityFile may use the tilde syntax to refer to a user's home directory or the tokens described in the TOKENS section.

             It is possible to have multiple identity files specified in configuration files; all these identities will be tried in sequence.  Multiple
             IdentityFile directives will add to the list of identities tried (this behaviour differs from that of other configuration directives).

             IdentityFile may be used in conjunction with IdentitiesOnly to select which identities in an agent are offered during authentication.  IdentityFile
             may also be used in conjunction with CertificateFile in order to provide any certificate also needed for authentication with the identity.
```

So it does seem like we need some way to find all matches, or continue searching the file after finding one match.

**Comment by wayneashleyberry** [comment]
Ah yes

> all these identities will be tried in sequence

That makes sense.

**Comment by kevinburke** [comment]
For the moment I think the way that you have it currently - iterate over hosts until you identify the matches - is probably best for what you are trying to do.

**Comment by lschapker** [comment]
There is a similar problem with the entry config "User" (i.e. change/add "IdentityFile ~/.ssh/id_rsa" with "User ABC" in the "*" and change/add "IdentityFile ~/.ssh/bar" with "User root".

My understanding is that "Host *" sets the defaults for all hosts and then if a secondary host matches, those new values over write the previous set defaults.  But this would only be possible if the host list is sorted with "*" being the first entry, you  read through the entire file, and the last value is returned.

The "ssh" command in centos (and I presume others) actually works this way.

**Comment by joegrasse** [comment]
For the issue that @wayneashleyberry originally brought up, I believe the return value is correct. That is if you want the package to act like ssh would.

From the man page.
```
     For each parameter, the first obtained value will be used.  The configuration files contain sections separated by “Host” specifications, and that section is only applied for hosts that match one of the pat-
     terns given in the specification.  The matched host name is the one given on the command line.

     Since the first obtained value for each parameter is used, more host-specific declarations should be given near the beginning of the file, and general defaults at the end.
```
