### ISSUE TITLE
Interact with comments as data

### ISSUE THREAD

**Issue by jtagcat** [kevinburke/ssh_config#36]
I'd like to use comments under hosts as custom configuration options, kind of like `X-` headers are used.

I might end up implementing this myself.

**Comment by jtagcat** [comment]
Hm, I expected something similar to `encoding/json`, a driver between a config file, and a go value (and converting with (un)marshal). As it is now, ssh_config doesn't look very useful, for non-comments either.

Closing this for now, as likely others don't have same crazy ideas I have.

**Comment by kevinburke** [comment]
There's an example given in the README of how to manipulate a file... the parser format is similar to HCL.
