### ISSUE TITLE
Trailing whitespaces in ssh configs should be ignored

### ISSUE THREAD

**Issue by codablock** [kevinburke/ssh_config#42]
I stumbled across this due to a machine that was not able to resolve a ssh hostname. It turned out that it was looking up the host in the ~/.ssh/config and then overriding the HostName with the value set in the config. This value turned out to have a trailing space, which was not trimmed and thus lead to an invalid hostname.

Looking into the [openssh code](https://github.com/openssh/openssh-portable/blob/master/readconf.c#L969), it seems to trim trailing whitespaces on a line level. I assume this library should adopt this behaviour.

**Comment by kevinburke** [comment]
Thanks for the report, I'm looking into this.

**Comment by kevinburke** [comment]
This should be fixed by #46, I will release a new version shortly.

Can I ask how you found this library? Or what software you were using that was behaving poorly?

**Comment by kevinburke** [comment]
Makes sense. I submitted a patch against go-git to update their dependency, but in the meantime you should be able to upgrade the indirect dependency to 1.2 and it should fix the issue.
