### ISSUE TITLE
Make UserSettings mockable

### ISSUE THREAD

**Issue by gandarez** [kevinburke/ssh_config#48]
The current implementation does not allow to pass a different ssh config file other than the default ones `~/.ssh/config` and `/etc/ssh/ssh_config`. It's really annoying because there's no possibility to mock these paths when calling `Get` or `GetStrict` in tests. Also `userConfigFinder` and `systemConfigFinder` can become public to use as a fallback function.

suggestion:
```Go
func NewUserSettings(systemConfigFinder, userConfigFinder func() string, ignoreErrors bool) *UserSettings {
	return &UserSettings{
		IgnoreErrors:       ignoreErrors,
		systemConfigFinder: systemConfigFinder,
		userConfigFinder:   userConfigFinder,
	}
}
```

**Comment by alanhamlett** [comment]
Thank you! This helps prevent dangerous side-effects in our tests so running locally doesn't risk clobbering your known hosts or local ssh config. (https://github.com/wakatime/wakatime-cli/pull/744)
