### ISSUE TITLE
tfsec error (undefined: os.ReadFile)

### ISSUE THREAD

**Issue by Tommy-Hasert** [kevinburke/ssh_config#51]
Unfortunately, the ssh_config package always causes the following error in the tfsec analysis (https://github.com/aquasecurity/tfsec).

`# github.com/kevinburke/ssh_config
/root/go/pkg/mod/github.com/kevinburke/ssh_config@v1.2.0/config.go:281:12: undefined: os.ReadFile
/root/go/pkg/mod/github.com/kevinburke/ssh_config@v1.2.0/config.go:296:12: undefined: io.ReadAll`

Is there a solution to this?

**Comment by kevinburke** [comment]
Hey, the solution is to upgrade to Go 1.16 or newer, which contains the new `os.ReadFile` function. Otherwise you should be able to use an older version of ssh_config.
