### ISSUE TITLE
Do not output default values (when defaults change there is probably a reason)

### ISSUE THREAD

**Issue by khm** [kevinburke/ssh_config#8]
The readme says:

> If we can't find a value for the given Host/keyword pair, and a default exists for the keyword, we return it.

Is this intended to explicitly set default values?  If so, that's a bad idea -- if a default needs to change, you now have to go back through every config touched by this tool and regenerate it.    That might be easy in a continuous-deployment setting, but in all settings that don't benefit from CD this is a liability.  Distributed packages or containers involving this sort of output will be needlessly difficult, and it reduces the composability of deploying configurations.

Please consider at least making this behavior controllable.

**Comment by kevinburke** [comment]
Hey! Thanks for writing.

I'm a little confused about your comment. The defaults are never *set*; if you try to retrieve a value from a Config or a UserSettings, and the keyword you asked for doesn't exist in the config, we return a default (if one exists for the keyword).

We don't ever set defaults in parsed config files, or overwrite values that exist in a file.

**Comment by kevinburke** [comment]
now I am worried the API's are not very good :(

**Comment by khm** [comment]
Yeah, I may have been unclear because this sort of thing is a phrasing minefield.   I'll try to clarify:

If I use the example code in the readme, that should read a config file and then write it back out.  You're now saying the written-out copy of the config file produced by `fmt.Println(cfg.String())` will _only_ contain configuration directives that were _explicitly_ set during `cfg, _ := ssh_config.Decode(f)`?

So excluding formatting, the config we get out will contain _only_ the values we read in?

**Comment by kevinburke** [comment]
That's correct!

**Comment by khm** [comment]
Perfect.  The way the description was written made it sound like default values would be introduced into the output (thereby hardcoding them in the output without deliberate intent).  

If that's not the case, there's no issue here!  Sorry for the noise.
