### ISSUE TITLE
Should be package sshconfig

### ISSUE THREAD

**Issue by peterbourgon** [kevinburke/ssh_config#9]
> By convention, packages are given lower case, single-word names; there should be no need for underscores or mixedCaps.

https://golang.org/doc/effective_go.html#package-names

**Comment by kevinburke** [comment]
I know, but I thought I'd match the name of the file on disk... `/etc/ssh/ssh_config` and the name of the manpage, `man ssh_config`. I guess it will probably trip up people either way.

**Comment by peterbourgon** [comment]
It's obviously your call :) but I don't think that pattern holds for any other similar package. When in Go, do as Gophers do?
